from . import mesob_inventory_major_classification
from . import mesob_inventory_sub_classification
from . import mesob_department
from . import mesob_item_code_sequence
from . import mesob_inventory_item
from . import mesob_inventory_requisition
from . import mesob_inventory_requisition_line
from . import mesob_inventory_receiving
from . import mesob_inventory_receiving_line
from . import mesob_inventory_model19
from . import mesob_inventory_model19_line
from . import mesob_inventory_dsr
from . import mesob_inventory_dsr_line
from . import mesob_inventory_issue_voucher
from . import mesob_gate_pass
from . import mesob_gate_pass_line
from . import mesob_bin_card
from . import mesob_stock_record_card
from . import mesob_stock_reorder_alert
from . import res_partner
from . import res_users
from . import mesob_procurement
from . import mesob_stock_taking
from . import mesob_stock_handover
from . import mesob_storage_security
from . import mesob_asset_dashboard
from . import mesob_asset_auto_register
