# -*- coding: utf-8 -*-
"""AUTO-055: Stock Accuracy Scorecard

Monthly stock accuracy monitoring with accuracy score calculation and trend analysis.
Complies with FR-REP-003.
"""

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError
from datetime import datetime, timedelta
import logging

_logger = logging.getLogger(__name__)


class MesobStockAccuracyScorecard(models.Model):
    """AUTO-055: Stock Accuracy Scorecard (FR-REP-003)."""
    
    _name = 'mesob.stock.accuracy.scorecard'
    _description = 'Stock Accuracy Scorecard'
    _order = 'scorecard_date desc, id desc'
    _rec_name = 'display_name'
    
    # Header
    name = fields.Char(string='Scorecard Reference', required=True, copy=False, default='New')
    scorecard_date = fields.Date(string='Scorecard Date', required=True, default=fields.Date.context_today)
    period_month = fields.Selection([
        ('1', 'January'), ('2', 'February'), ('3', 'March'),
        ('4', 'April'), ('5', 'May'), ('6', 'June'),
        ('7', 'July'), ('8', 'August'), ('9', 'September'),
        ('10', 'October'), ('11', 'November'), ('12', 'December'),
    ], string='Month', required=True)
    period_year = fields.Char(string='Year', required=True, default=lambda self: str(fields.Date.today().year))
    
    # Scope
    classification_id = fields.Many2one('mesob.inventory.major.classification', string='Classification (Optional)')
    location = fields.Char(string='Location (Optional)', help='Filter by storage location')
    
    # Accuracy Lines (Item-Level)
    accuracy_line_ids = fields.One2many(
        'mesob.stock.accuracy.scorecard.line',
        'scorecard_id',
        string='Item Accuracy Lines'
    )
    
    # Overall Metrics (AUTO-055)
    total_items_counted = fields.Integer(
        string='Total Items Counted',
        compute='_compute_accuracy_metrics',
        store=True,
        help='Total number of items in stock taking'
    )
    items_accurate = fields.Integer(
        string='Items Accurate (Zero Variance)',
        compute='_compute_accuracy_metrics',
        store=True,
        help='Number of items with no discrepancy between physical and system'
    )
    items_with_variance = fields.Integer(
        string='Items with Variance',
        compute='_compute_accuracy_metrics',
        store=True
    )
    
    # Accuracy Score (AUTO-055)
    accuracy_score = fields.Float(
        string='Accuracy Score (%)',
        compute='_compute_accuracy_metrics',
        store=True,
        help='AUTO-055: (Items Accurate / Total Items) × 100'
    )
    accuracy_rating = fields.Selection([
        ('excellent', 'Excellent (≥98%)'),
        ('good', 'Good (95-98%)'),
        ('fair', 'Fair (90-95%)'),
        ('poor', 'Poor (<90%)'),
    ], string='Accuracy Rating', compute='_compute_accuracy_rating', store=True)
    
    # Variance Analysis
    total_variance_quantity = fields.Float(
        string='Total Variance Qty',
        compute='_compute_variance_analysis',
        store=True,
        digits='Product Unit of Measure',
        help='Sum of absolute variance quantities'
    )
    total_variance_value = fields.Monetary(
        string='Total Variance Value (ETB)',
        compute='_compute_variance_analysis',
        store=True,
        currency_field='currency_id',
        help='Total monetary impact of variances'
    )
    currency_id = fields.Many2one('res.currency', string='Currency', default=lambda self: self.env.company.currency_id)
    
    # Top Discrepancies (for investigation)
    top_10_discrepancies = fields.Text(
        string='Top 10 Discrepancies',
        compute='_compute_top_discrepancies',
        help='Items with largest variance for PAO investigation'
    )
    
    # Trend Comparison
    previous_month_score = fields.Float(
        string='Previous Month Score',
        compute='_compute_trend',
        help='Accuracy score from previous month for trend analysis'
    )
    trend_direction = fields.Selection([
        ('improving', '📈 Improving'),
        ('stable', '➖ Stable'),
        ('declining', '📉 Declining'),
    ], string='Trend', compute='_compute_trend')
    trend_change = fields.Float(
        string='Trend Change (%)',
        compute='_compute_trend',
        help='Change from previous month'
    )
    
    # Tracking
    display_name = fields.Char(string='Display Name', compute='_compute_display_name', store=True)
    created_by_id = fields.Many2one('res.users', string='Generated By', default=lambda self: self.env.user)
    state = fields.Selection([
        ('draft', 'Draft'),
        ('calculated', 'Calculated'),
        ('reviewed', 'Reviewed by PAO'),
    ], string='Status', default='draft', tracking=True)
    
    # Report Output
    scorecard_report = fields.Html(
        string='Scorecard Report',
        compute='_compute_scorecard_report',
        help='AUTO-055: Visual accuracy scorecard with trend analysis (FR-REP-003)'
    )
    
    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', 'New') == 'New':
                month = vals.get('period_month', '1')
                year = vals.get('period_year', '2026')
                vals['name'] = f'SAS/{year}/{month.zfill(2)}'
        return super().create(vals_list)
    
    @api.depends('period_month', 'period_year')
    def _compute_display_name(self):
        months = dict(self._fields['period_month'].selection)
        for rec in self:
            month_name = months.get(rec.period_month, rec.period_month)
            rec.display_name = f'Stock Accuracy Scorecard: {month_name} {rec.period_year}'
    
    @api.depends('accuracy_line_ids.is_accurate')
    def _compute_accuracy_metrics(self):
        """AUTO-055: Calculate overall accuracy score (FR-REP-003)."""
        for rec in self:
            lines = rec.accuracy_line_ids
            rec.total_items_counted = len(lines)
            
            if rec.total_items_counted > 0:
                rec.items_accurate = len(lines.filtered('is_accurate'))
                rec.items_with_variance = rec.total_items_counted - rec.items_accurate
                rec.accuracy_score = (rec.items_accurate / rec.total_items_counted) * 100.0
            else:
                rec.items_accurate = 0
                rec.items_with_variance = 0
                rec.accuracy_score = 0.0
            
            _logger.info(
                f'AUTO-055: Stock accuracy calculated for {rec.period_month}/{rec.period_year} - '
                f'Score: {rec.accuracy_score:.1f}%, {rec.items_accurate}/{rec.total_items_counted} items accurate'
            )
    
    @api.depends('accuracy_score')
    def _compute_accuracy_rating(self):
        """AUTO-055: Classify accuracy into rating bands."""
        for rec in self:
            score = rec.accuracy_score
            if score >= 98:
                rec.accuracy_rating = 'excellent'
            elif score >= 95:
                rec.accuracy_rating = 'good'
            elif score >= 90:
                rec.accuracy_rating = 'fair'
            else:
                rec.accuracy_rating = 'poor'
    
    @api.depends('accuracy_line_ids.variance_quantity', 'accuracy_line_ids.variance_value')
    def _compute_variance_analysis(self):
        """Calculate total variance quantities and values."""
        for rec in self:
            rec.total_variance_quantity = sum(abs(line.variance_quantity) for line in rec.accuracy_line_ids)
            rec.total_variance_value = sum(abs(line.variance_value) for line in rec.accuracy_line_ids)
    
    @api.depends('accuracy_line_ids.variance_percentage')
    def _compute_top_discrepancies(self):
        """Identify top 10 items with largest variance for investigation."""
        for rec in self:
            # Sort by absolute variance percentage descending
            top_lines = rec.accuracy_line_ids.sorted(
                key=lambda l: abs(l.variance_percentage),
                reverse=True
            )[:10]
            
            if top_lines:
                summary = 'Top 10 Items Requiring Investigation:\n'
                for idx, line in enumerate(top_lines, 1):
                    summary += f'{idx}. {line.item_code} - {line.item_name}: {line.variance_percentage:+.1f}% variance\n'
                rec.top_10_discrepancies = summary
            else:
                rec.top_10_discrepancies = 'No discrepancies found.'
    
    @api.depends('accuracy_score', 'period_month', 'period_year')
    def _compute_trend(self):
        """AUTO-055: Calculate trend vs previous month for continuous improvement tracking."""
        for rec in self:
            # Find previous month's scorecard
            current_month = int(rec.period_month)
            current_year = int(rec.period_year)
            
            if current_month == 1:
                prev_month = 12
                prev_year = current_year - 1
            else:
                prev_month = current_month - 1
                prev_year = current_year
            
            previous_scorecard = self.search([
                ('period_month', '=', str(prev_month)),
                ('period_year', '=', str(prev_year)),
                ('state', 'in', ['calculated', 'reviewed']),
            ], limit=1)
            
            if previous_scorecard:
                rec.previous_month_score = previous_scorecard.accuracy_score
                rec.trend_change = rec.accuracy_score - previous_scorecard.accuracy_score
                
                # Determine trend direction
                if rec.trend_change >= 2.0:
                    rec.trend_direction = 'improving'
                elif rec.trend_change <= -2.0:
                    rec.trend_direction = 'declining'
                else:
                    rec.trend_direction = 'stable'
            else:
                rec.previous_month_score = 0.0
                rec.trend_change = 0.0
                rec.trend_direction = 'stable'
    
    @api.depends('accuracy_score', 'accuracy_rating', 'trend_direction')
    def _compute_scorecard_report(self):
        """AUTO-055: Generate visual accuracy scorecard report."""
        months = dict(self._fields['period_month'].selection)
        
        for rec in self:
            if not rec.accuracy_line_ids:
                rec.scorecard_report = '<p><em>No accuracy data available. Click "Calculate Scorecard" to analyze stock taking results.</em></p>'
                continue
            
            month_name = months.get(rec.period_month, rec.period_month)
            
            # Rating color
            rating_colors = {
                'excellent': '#28a745',
                'good': '#5cb85c',
                'fair': '#ffc107',
                'poor': '#dc3545',
            }
            rating_color = rating_colors.get(rec.accuracy_rating, '#6c757d')
            
            # Trend color and icon
            trend_colors = {
                'improving': '#28a745',
                'stable': '#6c757d',
                'declining': '#dc3545',
            }
            trend_color = trend_colors.get(rec.trend_direction, '#6c757d')
            trend_label = dict(rec._fields['trend_direction'].selection).get(rec.trend_direction, '')
            
            html = f'''
            <div style="font-family: Arial, sans-serif; padding: 20px;">
                <h2 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">
                    AUTO-055: Stock Accuracy Scorecard
                </h2>
                
                <div style="background-color: #e7f3ff; padding: 15px; margin: 15px 0; border-left: 4px solid #2196f3;">
                    <h3 style="margin-top: 0; color: #0c5460;">📅 Period Information</h3>
                    <table style="width: 100%; margin-top: 10px;">
                        <tr>
                            <td style="padding: 5px;"><strong>Month:</strong></td>
                            <td style="padding: 5px;">{month_name} {rec.period_year}</td>
                        </tr>
                        <tr>
                            <td style="padding: 5px;"><strong>Report Date:</strong></td>
                            <td style="padding: 5px;">{rec.scorecard_date}</td>
                        </tr>
                        <tr>
                            <td style="padding: 5px;"><strong>Generated By:</strong></td>
                            <td style="padding: 5px;">{rec.created_by_id.name}</td>
                        </tr>
                        {f'<tr><td style="padding: 5px;"><strong>Classification:</strong></td><td style="padding: 5px;">{rec.classification_id.name}</td></tr>' if rec.classification_id else ''}
                        {f'<tr><td style="padding: 5px;"><strong>Location:</strong></td><td style="padding: 5px;">{rec.location}</td></tr>' if rec.location else ''}
                    </table>
                </div>
                
                <!-- Accuracy Score Card -->
                <div style="background-color: {rating_color}15; border-left: 4px solid {rating_color}; padding: 20px; margin: 15px 0;">
                    <div style="text-align: center;">
                        <h1 style="margin: 0; font-size: 72px; color: {rating_color};">{rec.accuracy_score:.1f}%</h1>
                        <h3 style="margin: 10px 0; color: {rating_color};">{dict(rec._fields['accuracy_rating'].selection).get(rec.accuracy_rating, '')}</h3>
                        <p style="margin: 0; color: #6c757d; font-size: 14px;">Stock Accuracy Score</p>
                    </div>
                </div>
                
                <!-- Metrics Summary -->
                <h3 style="color: #2c3e50; margin-top: 25px;">📊 Accuracy Metrics</h3>
                <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
                    <tr style="background-color: #ecf0f1;">
                        <td style="border: 1px solid #bdc3c7; padding: 12px; width: 60%;"><strong>Total Items Counted</strong></td>
                        <td style="border: 1px solid #bdc3c7; padding: 12px; text-align: center; font-weight: bold; font-size: 18px;">{rec.total_items_counted}</td>
                    </tr>
                    <tr style="background-color: #d4edda;">
                        <td style="border: 1px solid #bdc3c7; padding: 12px;"><strong>✅ Items Accurate (Zero Variance)</strong></td>
                        <td style="border: 1px solid #bdc3c7; padding: 12px; text-align: center; font-weight: bold; font-size: 18px; color: #155724;">{rec.items_accurate}</td>
                    </tr>
                    <tr style="background-color: #f8d7da;">
                        <td style="border: 1px solid #bdc3c7; padding: 12px;"><strong>❌ Items with Variance</strong></td>
                        <td style="border: 1px solid #bdc3c7; padding: 12px; text-align: center; font-weight: bold; font-size: 18px; color: #721c24;">{rec.items_with_variance}</td>
                    </tr>
                    <tr style="background-color: #fff3cd;">
                        <td style="border: 1px solid #bdc3c7; padding: 12px;"><strong>Total Variance Value</strong></td>
                        <td style="border: 1px solid #bdc3c7; padding: 12px; text-align: center; font-weight: bold; font-size: 16px; color: #856404;">ETB {rec.total_variance_value:,.2f}</td>
                    </tr>
                </table>
            '''
            
            # Trend Analysis
            if rec.previous_month_score > 0:
                html += f'''
                <h3 style="color: #2c3e50; margin-top: 25px;">📈 Trend Analysis</h3>
                <div style="background-color: {trend_color}15; border-left: 4px solid {trend_color}; padding: 15px; margin-top: 10px;">
                    <table style="width: 100%;">
                        <tr>
                            <td style="padding: 8px;"><strong>Previous Month Score:</strong></td>
                            <td style="padding: 8px; text-align: right;">{rec.previous_month_score:.1f}%</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px;"><strong>Current Month Score:</strong></td>
                            <td style="padding: 8px; text-align: right;">{rec.accuracy_score:.1f}%</td>
                        </tr>
                        <tr style="background-color: {trend_color}30;">
                            <td style="padding: 10px; font-weight: bold;"><strong>Trend:</strong></td>
                            <td style="padding: 10px; text-align: right; font-weight: bold; color: {trend_color}; font-size: 18px;">
                                {trend_label} ({rec.trend_change:+.1f}%)
                            </td>
                        </tr>
                    </table>
                </div>
                '''
            
            # Top Discrepancies Table
            top_lines = rec.accuracy_line_ids.filtered(lambda l: not l.is_accurate).sorted(
                key=lambda l: abs(l.variance_percentage),
                reverse=True
            )[:10]
            
            if top_lines:
                html += '''
                <h3 style="color: #dc3545; margin-top: 30px;">🔍 Top 10 Items Requiring Investigation</h3>
                <table style="width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px;">
                    <thead style="background-color: #dc3545; color: white;">
                        <tr>
                            <th style="border: 1px solid #721c24; padding: 8px; text-align: left;">#</th>
                            <th style="border: 1px solid #721c24; padding: 8px; text-align: left;">Item Code</th>
                            <th style="border: 1px solid #721c24; padding: 8px; text-align: left;">Item Name</th>
                            <th style="border: 1px solid #721c24; padding: 8px; text-align: right;">System Qty</th>
                            <th style="border: 1px solid #721c24; padding: 8px; text-align: right;">Physical Qty</th>
                            <th style="border: 1px solid #721c24; padding: 8px; text-align: right;">Variance</th>
                            <th style="border: 1px solid #721c24; padding: 8px; text-align: right;">Variance %</th>
                        </tr>
                    </thead>
                    <tbody>
                '''
                
                for idx, line in enumerate(top_lines, 1):
                    variance_color = '#dc3545' if line.variance_quantity < 0 else '#ffc107'
                    html += f'''
                    <tr style="background-color: {variance_color}10;">
                        <td style="border: 1px solid #bdc3c7; padding: 6px; text-align: center; font-weight: bold;">{idx}</td>
                        <td style="border: 1px solid #bdc3c7; padding: 6px;">{line.item_code}</td>
                        <td style="border: 1px solid #bdc3c7; padding: 6px;">{line.item_name[:40]}...</td>
                        <td style="border: 1px solid #bdc3c7; padding: 6px; text-align: right;">{line.system_quantity:.2f}</td>
                        <td style="border: 1px solid #bdc3c7; padding: 6px; text-align: right;">{line.physical_quantity:.2f}</td>
                        <td style="border: 1px solid #bdc3c7; padding: 6px; text-align: right; color: {variance_color}; font-weight: bold;">{line.variance_quantity:+.2f}</td>
                        <td style="border: 1px solid #bdc3c7; padding: 6px; text-align: right; color: {variance_color}; font-weight: bold;">{line.variance_percentage:+.1f}%</td>
                    </tr>
                    '''
                
                html += '''
                    </tbody>
                </table>
                '''
            
            html += '''
                <div style="background-color: #e7f3ff; border-left: 4px solid #2196f3; padding: 15px; margin-top: 25px;">
                    <h4 style="margin-top: 0; color: #0c5460;">📋 FR-REP-003 Compliance</h4>
                    <p style="color: #0c5460; margin: 0;">
                        This monthly stock accuracy scorecard supports continuous improvement per FR-REP-003.
                        <br/><br/>
                        <strong>Target:</strong> ≥98% accuracy (Excellent)
                        <br/><strong>Action:</strong> Items with variance flagged for FR-ST-007 corrective action investigation.
                    </p>
                </div>
                
                <div style="margin-top: 30px; padding-top: 15px; border-top: 1px solid #bdc3c7; color: #7f8c8d; font-size: 12px;">
                    <p><em>AUTO-055: Scorecard auto-generated monthly from stock taking results.</em></p>
                    <p><em>Trend tracking enables proactive process improvement and identifies recurring accuracy issues.</em></p>
                </div>
            </div>
            '''
            
            rec.scorecard_report = html
    
    def action_calculate_scorecard(self):
        """AUTO-055: Calculate accuracy scorecard from stock taking results."""
        self.ensure_one()
        
        # Clear existing lines
        self.accuracy_line_ids.unlink()
        
        # Query stock taking results for this month
        # Note: Replace with actual stock taking model query
        month_start = datetime(int(self.period_year), int(self.period_month), 1).date()
        if int(self.period_month) == 12:
            month_end = datetime(int(self.period_year) + 1, 1, 1).date() - timedelta(days=1)
        else:
            month_end = datetime(int(self.period_year), int(self.period_month) + 1, 1).date() - timedelta(days=1)
        
        # Find stock taking records in this period
        stock_takings = self.env['mesob.stock.taking'].search([
            ('date', '>=', month_start),
            ('date', '<=', month_end),
            ('state', '=', 'completed'),  # Only completed stock takings
        ])
        
        _logger.info(f'AUTO-055: Found {len(stock_takings)} completed stock taking(s) for {self.period_month}/{self.period_year}')
        
        # Process stock taking lines and create accuracy lines
        # Placeholder: In production, iterate through stock_taking.line_ids
        
        self.state = 'calculated'
        
        _logger.info(
            f'AUTO-055: Scorecard calculated - '
            f'{self.accuracy_score:.1f}% accuracy, {self.items_with_variance} discrepancies'
        )
        
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'Scorecard Calculated',
                'message': f'Accuracy Score: {self.accuracy_score:.1f}% ({dict(self._fields["accuracy_rating"].selection).get(self.accuracy_rating, "")})',
                'type': 'success' if self.accuracy_score >= 95 else 'warning',
                'sticky': False,
            }
        }
    
    def action_pao_review(self):
        """PAO reviews and acknowledges accuracy scorecard."""
        self.ensure_one()
        
        if self.state != 'calculated':
            raise ValidationError('Please calculate scorecard before reviewing.')
        
        self.state = 'reviewed'
        
        self.message_post(
            body=f'''<div style="background-color: #e7f3ff; padding: 15px; border-left: 4px solid #2196f3;">
                <h3>✅ Stock Accuracy Scorecard Reviewed</h3>
                <p><strong>Period:</strong> {dict(self._fields['period_month'].selection).get(self.period_month)} {self.period_year}</p>
                <p><strong>Accuracy Score:</strong> {self.accuracy_score:.1f}% ({dict(self._fields['accuracy_rating'].selection).get(self.accuracy_rating)})</p>
                <p><strong>Items with Variance:</strong> {self.items_with_variance}</p>
                <p><em>Reviewed by: {self.env.user.name} on {fields.Date.today()}</em></p>
            </div>''',
            subject='Stock Accuracy Scorecard Reviewed',
        )
        
        return True
    
    @api.model
    def _cron_generate_monthly_scorecard(self):
        """AUTO-055: Cron job to auto-generate monthly stock accuracy scorecard.
        
        Runs on 1st of each month to generate scorecard for previous month.
        """
        try:
            # Calculate previous month
            today = fields.Date.today()
            if today.month == 1:
                prev_month = 12
                prev_year = today.year - 1
            else:
                prev_month = today.month - 1
                prev_year = today.year
            
            # Check if scorecard already exists for previous month
            existing = self.search([
                ('period_month', '=', str(prev_month)),
                ('period_year', '=', str(prev_year)),
            ])
            
            if existing:
                _logger.info(
                    f'AUTO-055 Cron: Scorecard already exists for {prev_month}/{prev_year} - Skipping'
                )
                return
            
            # Create new scorecard
            scorecard = self.create({
                'period_month': str(prev_month),
                'period_year': str(prev_year),
                'scorecard_date': today,
            })
            
            # Calculate scorecard from stock taking data
            scorecard.action_calculate_scorecard()
            
            # Send notification to PAO
            pao_users = self.env.ref('mesob_inventory_base.group_mesob_pao').users
            
            if pao_users:
                scorecard.message_post(
                    body=f'''<div style="background-color: #fff3cd; padding: 15px; border-left: 4px solid #ffc107;">
                        <h3>📊 Monthly Stock Accuracy Scorecard Generated</h3>
                        <p><strong>Period:</strong> {dict(self._fields['period_month'].selection).get(str(prev_month))} {prev_year}</p>
                        <p><strong>Accuracy Score:</strong> {scorecard.accuracy_score:.1f}% ({dict(self._fields['accuracy_rating'].selection).get(scorecard.accuracy_rating)})</p>
                        <p><strong>Items with Variance:</strong> {scorecard.items_with_variance}</p>
                        <p><em>Auto-generated by AUTO-055 cron job on {today}</em></p>
                        <p><strong>Action Required:</strong> Please review scorecard and investigate top discrepancies.</p>
                    </div>''',
                    subject=f'Monthly Stock Accuracy Scorecard: {prev_month}/{prev_year}',
                    partner_ids=pao_users.mapped('partner_id').ids,
                )
            
            _logger.info(
                f'AUTO-055 Cron: Generated scorecard for {prev_month}/{prev_year} - '
                f'Score: {scorecard.accuracy_score:.1f}%, {scorecard.items_with_variance} discrepancies'
            )
            
        except Exception as e:
            _logger.error(f'AUTO-055 Cron: Failed to generate monthly scorecard: {e}', exc_info=True)
            # Don't raise - allow cron to continue running


class MesobStockAccuracyScorecardLine(models.Model):
    """AUTO-055: Individual item accuracy record."""
    
    _name = 'mesob.stock.accuracy.scorecard.line'
    _description = 'Stock Accuracy Scorecard Line'
    _order = 'variance_percentage desc, item_code'
    
    scorecard_id = fields.Many2one(
        'mesob.stock.accuracy.scorecard',
        string='Scorecard',
        required=True,
        ondelete='cascade'
    )
    
    # Item Information
    item_id = fields.Many2one('mesob.inventory.item', string='Item')
    item_code = fields.Char(string='Item Code', required=True)
    item_name = fields.Char(string='Item Name', required=True)
    classification_id = fields.Many2one('mesob.inventory.major.classification', string='Classification')
    
    # Stock Taking Data
    stock_taking_ref = fields.Char(string='Stock Taking Reference')
    stock_taking_date = fields.Date(string='Stock Taking Date')
    
    # Quantities
    system_quantity = fields.Float(
        string='System Quantity (Records)',
        digits='Product Unit of Measure',
        required=True,
        help='Quantity per stock records before counting'
    )
    physical_quantity = fields.Float(
        string='Physical Count',
        digits='Product Unit of Measure',
        required=True,
        help='Actual physical count during stock taking'
    )
    variance_quantity = fields.Float(
        string='Variance',
        compute='_compute_variance',
        store=True,
        digits='Product Unit of Measure',
        help='Physical - System (positive = surplus, negative = shortage)'
    )
    variance_percentage = fields.Float(
        string='Variance %',
        compute='_compute_variance',
        store=True,
        help='(Variance / System) × 100'
    )
    
    # Value Impact
    unit_cost = fields.Monetary(string='Unit Cost', currency_field='currency_id')
    variance_value = fields.Monetary(
        string='Variance Value',
        compute='_compute_variance_value',
        store=True,
        currency_field='currency_id',
        help='Variance Qty × Unit Cost'
    )
    currency_id = fields.Many2one('res.currency', string='Currency', default=lambda self: self.env.company.currency_id)
    
    # Accuracy Flag
    is_accurate = fields.Boolean(
        string='Accurate',
        compute='_compute_is_accurate',
        store=True,
        help='True if variance is zero (within tolerance)'
    )
    
    # Corrective Action
    corrective_action = fields.Text(string='Corrective Action Taken')
    action_date = fields.Date(string='Action Date')
    
    @api.depends('system_quantity', 'physical_quantity')
    def _compute_variance(self):
        """Calculate variance quantity and percentage."""
        for line in self:
            line.variance_quantity = line.physical_quantity - line.system_quantity
            
            if line.system_quantity != 0:
                line.variance_percentage = (line.variance_quantity / line.system_quantity) * 100.0
            else:
                line.variance_percentage = 0.0 if line.physical_quantity == 0 else 100.0
    
    @api.depends('variance_quantity', 'unit_cost')
    def _compute_variance_value(self):
        """Calculate monetary value of variance."""
        for line in self:
            line.variance_value = line.variance_quantity * line.unit_cost
    
    @api.depends('variance_quantity')
    def _compute_is_accurate(self):
        """Determine if item is accurate (zero variance within tolerance)."""
        tolerance = 0.01  # Tolerance for floating point comparison
        for line in self:
            line.is_accurate = (abs(line.variance_quantity) <= tolerance)
